### ISSUE TITLE
customize swipe-out btn

### ISSUE THREAD

**Issue by FrancescaBarbazeni** [silentcloud/react-native-swipeout#6]
hi,

there is a way to change the button's dimension? I need to change the button width for long text.

Thank you

**Comment by silentcloud** [comment]
@FrancescaBarbazeni https://github.com/silentcloud/react-native-swipeout/blob/master/index.js#L84

```js
var swipeoutBtns = [
  {
    text: 'Button',
    component: your/custom/btn/component
  }
]

// Swipeout component
<Swipeout right={swipeoutBtns}>
  <View>
    <Text>Swipe me left</Text>
  </View>
</Swipeout>
```

**Comment by FrancescaBarbazeni** [comment]
If I put the component inside the button in this way:

```
var swipeoutBtns = [
  {
    text: 'Button',
    component: this._renderBtn()
  }
]
```
_renderBtn = () => (
<View style={{width: 500, height: 500}}>
     <Text>custom dimension</Text>
 </View>
);

It remains of the same dimensions. What's wrong with my code? 
Thank you
