### ISSUE TITLE
Text wrapping when hiding button

### ISSUE THREAD

**Issue by vTrip** [silentcloud/react-native-swipeout#7]
The text inside the button is wrapping to multiple lines as you slide to close

**Comment by vTrip** [comment]
![simulator screen shot 4 apr 2017 5 40 31 pm](https://cloud.githubusercontent.com/assets/15204972/24646086/0130fdca-195e-11e7-98b5-d093a4f8cdd0.png)

**Comment by jqn** [comment]
That would be great and a lot nicer.

**Comment by silentcloud** [comment]
https://github.com/dancormier/react-native-swipeout/issues/141
